package:
    name: 'occupationcoder'
    version: '1.0.0'


requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - pandas >=0.20.2
        - dask >=0.13.0
        - fuzzywuzzy >=0.15.1
        - scikit-learn >=0.19.1
        - nltk >=3.2.2
source:
  path: ../

about:
    license: 'Apache2'
    summary : 'A tool to use job text, such as job description, to assign standard occupational classification codes. '
    home : 'https://github.com/aeturrell/occupationcoder'